### ISSUE TITLE
nheko segmentation fault with Kvantum Qt style

### ISSUE THREAD

**Issue by alexminder** [mujx/nheko#297]
### System:

- Nheko commit/version: net-im/nheko-0.2.0
- Kvantum Qt style version: x11-themes/kvantum-0.10.5
- Installation method: Gentoo portage nheko overlay
- Operating System: Gentoo Linux
- Qt version: dev-qt/qtcore-5.9.4-r2
- C++ compiler: sys-devel/gcc-6.4.0-r1
- Desktop Environment: KDE Plasma

### Actual behavior
When mouse over scrollbar nheko crashes.
### Expected behavior
No app crash.
### Steps to reproduce
- Install Qt kvantum style;
- Apply Kvantum style;
- Run nheko;
- Move mose on scrollbar;
- nheko crashes.

### Debugger backtrace 
[abrt.log](https://github.com/mujx/nheko/files/1895872/abrt.log)

**Comment by Hawkheart** [comment]
I ran into this issue (or a similar one) a few weeks back. I traced my crashes back to this if statement in Kvantum:
```
if (tspec_.scroll_arrows
          /* when arrows are present in a different style, as in Gwenview */
          || (widget && widget->style() != this
              && subControl != SC_ScrollBarSubLine && subControl != SC_ScrollBarAddLine // no infinite loop
              && widget->style()->subControlRect(CC_ScrollBar,option,SC_ScrollBarSubLine,widget).isValid())
```
(from https://github.com/tsujan/Kvantum/blob/master/Kvantum/style/Kvantum.cpp).

Particularly, the 'no infinite loop' check is failing and it seems to be recursing until the stack overflows.

**Comment by mujx** [comment]
@alexminder Could you try compiling the v0.3.0 version? The scrollbars are visible at all times now.

**Comment by alexminder** [comment]
Compiling finished with no success.
```
::events::msg::Redacted>, mtx::events::RoomEvent<mtx::events::msg::Audio>, mtx::events::RoomEvent<mtx::events::msg::Emote>, mtx::events::RoomEvent<mtx::events::msg::File>, mtx::events::RoomEvent<mtx::events::msg::Image>, mtx::events::RoomEvent<mtx::events::msg::Notice>, mtx::events::RoomEvent<mtx::events::msg::Text>, mtx::events::RoomEvent<mtx::events::msg::Video> > >&)::<lambda(const auto:10&)>]’
/var/tmp/portage/net-im/nheko-0.3.0/work/nheko-0.3.0/src/timeline/TimelineView.cc:799:10:   required from here
/var/tmp/portage/net-im/nheko-0.3.0/work/nheko-0.3.0/src/timeline/TimelineView.cc:798:60: error: cannot call member function ‘mtx::events::EventType TimelineView::getEventType(const TimelineEvents&) const’ without object
                 return mtx::events::EventType::RoomMessage == getEventType(event);
                                                             
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/bits/stl_algobase.h:71:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/algorithm:61,
                 from /usr/include/qt5/QtCore/qglobal.h:109,
                 from /usr/include/qt5/QtGui/qtguiglobal.h:43,
                 from /usr/include/qt5/QtWidgets/qtwidgetsglobal.h:43,
                 from /usr/include/qt5/QtWidgets/qapplication.h:43,
                 from /usr/include/qt5/QtWidgets/QApplication:1,
                 from /var/tmp/portage/net-im/nheko-0.3.0/work/nheko-0.3.0/src/timeline/TimelineView.cc:18:
```

**Comment by mujx** [comment]
That's the issue described in #298. You'll have to use gcc-7 or clang. It's also mentioned in the readme that the minimum supported gcc compiler is gcc-7.

**Comment by alexminder** [comment]
I will try nheko-0.3 later, when gcc-7 will be stable in Gentoo. 
For now I close the issue as crashes fixed in `kvantum`.
Thank you!

**Comment by mujx** [comment]
@alexminder You can also use clang.

**Comment by maxigaz** [comment]
I still have this problem in v0.5.0, installed from the [AUR](https://aur.archlinux.org/packages/nheko) in Manjaro Linux KDE. When kvantum is being used instead of Breeze, Nheko crashes when the mouse is over the scrollbar.

**Comment by mujx** [comment]
@maxigaz Are you using the latest kvantum version? If so and the problem persists it might better to open an issue on kvantum's tracker.

**Comment by Hawkheart** [comment]
Kvantum hasn't published a release since the issue was fixed in their
master, unfortunately. You'll have to build your own or wait for a new
release.

**Comment by maxigaz** [comment]
I've just tried the latest git version of kvantum, and I can confirm that Nheko no longer crashes. Thank you for the suggestion!
